export const FETCH_FACTS_START = "FETCH_FACTS_START";
export const FETCH_FACTS_SUCCESS = "FETCH_FACTS_SUCCESS";
export const FETCH_FACTS_FAILURE = "FETCH_FACTS_FAILURE";
export const LOAD_MORE_FACTS = "LOAD_MORE_FACTS";
